# Generated by Django 3.2 on 2021-04-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulink', models.CharField(max_length=10000)),
                ('uid', models.CharField(max_length=200)),
            ],
        ),
    ]
