# Generated by Django 3.2 on 2021-04-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='ulink',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='urls',
            old_name='uid',
            new_name='uuid',
        ),
    ]
